#
# This is the file your server opens to find the main class
# of your plugin and its information. We automatically replace
# many variables here from your pom.xml file.
#
# See https://www.spigotmc.org/wiki/plugin-yml/ for more
# information .
#
# NB: Please do not register commands here, these are done
# directly in our plugin using Foundation :)
#
name: ${project.name}
version: ${project.version}
main: ${main.class}
author: The Fallen
api-version: 1.13